### ISSUE TITLE
Quick change to an AddDependency recipe

### ISSUE THREAD

**Issue by traceyyoshima** [josemariavillar/test_project#1]
Hi @josemariavillar,
Thanks for all your help with issues on openrewrite - I have a quick request related to an AddDependency recipe:

The recipe to add `spring-cloud-starter-config` should be updated from `org.springframework.boot` to `org.springframework.cloud`:

```yaml 
  - org.openrewrite.maven.AddDependency:
      groupId: org.springframework.cloud
      artifactId: spring-cloud-starter-config
      version: 2.2.8.RELEASE
      onlyIfUsing: org.springframework.boot.*
```
